services:
  dashboard:
    # 'build: .' tells compose to use the Dockerfile in this directory
    build: .
    container_name: glassy-dashboard
    # You can name your image whatever you like
    image: ghcr.io/pixelw4rs/glassy-dashboard:latest
    ports:
      - "8585:80"
    restart: unless-stopped
